### ISSUE TITLE
SpringBoot 自动装配原理

### ISSUE THREAD

**Issue by qilihui** [qilihui/qilihui.github.io#7]
https://qilihui.github.io/SpringBoot-1/ 

 由于最近面试被问到 SpringBoot 自动装配原理，回答的稀碎，特地收集资料记录。

先看main方法

@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);//从run方法进去
    }

}

通过 refreshContext 加载主类注解

public ConfigurableApplicationContext run(String... args) {
       //省略......
        try {
       //省略......
            this.refreshContext(context); //通过这个方法加载入口类的注解
            this.afterRefresh(context, applicationArguments);
            stopWatch.stop();
            if (this.logStartupInfo) {
                (new StartupInfoLogger(this.mainApplicationClass)).logStarted(this.getApplicationLog(), stopWatch);
            }

            listeners.started(context);
            this.callRunners(context, applicationArguments);
        } catch (Throwable var10) {
            this.handleRunFailure(context, var10, exceptionReporters, listeners);
            throw new IllegalStateException(var10);
        }
       //省略......
    }

通过 入口类的@SpringBootApplication注解可以进入 @EnableAutoConfiguration 注解，可以看到@Import 注解加载了导入了 AutoConfigurationImportSelector 类

@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@AutoConfigurationPackage
@Import({AutoConfigurationImportSelector.class})
public @interface EnableAutoConfiguration {
    String ENABLED_OVERRIDE_PROPERTY =

**Comment by kilicmu** [comment]
好文，绝世好文，传世佳作，看得我简直涕泗横流，感动不已。简直太nb了。

**Comment by qilihui** [comment]
> @kilicmu
> 好文，绝世好文，传世佳作，看得我简直涕泗横流，感动不已。简直太nb了。

我垃圾

**Comment by kilicmu** [comment]
辉少我是你的舔狗啊，让我舔你ok不

**Comment by qilihui** [comment]
> @kilicmu
> 辉少我是你的舔狗啊，让我舔你ok不

2

**Comment by kilicmu** [comment]
> @qilihui
> > @kilicmu
> > 辉少我是你的舔狗啊，让我舔你ok不
> 
> 2

我明白，只有阿彪才能舔。真为你俩的爱情故事感动

**Comment by qilihui** [comment]
2

**Comment by qilihui** [comment]
> @kilicmu
> > @qilihui
> > > @kilicmu
> > > 辉少我是你的舔狗啊，让我舔你ok不
> > 
> > 2
> 
> 我明白，只有阿彪才能舔。真为你俩的爱情故事感动

2

**Comment by kilicmu** [comment]
真好，还是那么含蓄

**Comment by kilicmu** [comment]
以后我可以尊称你为您吗，这样就可以时时刻刻把您放在心里了

**Comment by kilicmu** [comment]
为啥我感觉你这个文的开头似曾相识

**Comment by kilicmu** [comment]
舔辉少就完事了
